// Regenerates syntaxes/gdscript-globals.injection.json from Godot's class reference, so calls to
// global functions (print, clamp, lerp, preload, ...) get Godot's global_function_color.
// Usage: node update-globals.mjs [godot tag, default 4.4-stable]
import fs from "node:fs";

const tag = process.argv[2] ?? "4.4-stable";
const sources = [
  `https://raw.githubusercontent.com/godotengine/godot/${tag}/doc/classes/@GlobalScope.xml`,
  `https://raw.githubusercontent.com/godotengine/godot/${tag}/modules/gdscript/doc_classes/@GDScript.xml`,
];

const names = new Set();
for (const url of sources) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  for (const m of (await res.text()).matchAll(/<method name="([^"]+)"/g)) names.add(m[1]);
}
// Longest first so e.g. "print_rich" wins over "print".
const list = [...names].sort((a, b) => b.length - a.length || a.localeCompare(b));

const grammar = {
  $comment: `Godot ${tag} global functions (@GlobalScope and @GDScript). Generated by test/visual/update-globals.mjs.`,
  scopeName: "source.gdscript.godot-globals.injection",
  injectionSelector: "L:source.gdscript -comment -string",
  patterns: [
    {
      // Only bare calls: not methods (node.print()) or node paths ($print).
      match: `(?<![.\\w$%@&^])(${list.join("|")})(?=\\s*\\()`,
      name: "support.function.builtin.gdscript",
    },
  ],
};
fs.writeFileSync(new URL("../../syntaxes/gdscript-globals.injection.json", import.meta.url), JSON.stringify(grammar, null, "\t") + "\n");
console.log(`Wrote ${list.length} global functions from Godot ${tag}`);
